package:
    name: root
    version: 6.04.02
source:
    #fn: root_v6.04.02.source.tar.gz
    #url: https://root.cern.ch/download/root_v6.04.02.source.tar.gz
    git_url: https://github.com/remenska/root
    git_tag: python3fixes
    #patches:
    #    - python3.patch
    #    - python3_set.patch
    #path: /home/daniela/anaconda_backup/anaconda/root-6.04.02
build:
    number: 9
    string: py34_gcc4.8
    
    detect_binary_files_with_prefix: True

requirements:
    build:
        - python 3.4*
        - openssl
        - qt
        - sqlite
        - fftw
        - pcre
        - libxml2
        - graphviz
        - cmake >=3.2.3
        #- gcc >=4.8  
    run:
        - python 3.4*
        - openssl
        - qt
        - sqlite
        - graphviz
        - libxml2
        - fftw
        - pcre
        - libgcc >=4.8

test:
    imports:

    commands:

about:
    home: http://root.cern.ch/
    license: LGPL v2.1

