{% set name = "extcats" %}
{% set version = "2.1" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "55231795a37d6a70ffa5ec5a3f0e4687a2a5bc7270d3849583964baf17580d53" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  noarch: python
  number: 1
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - setuptools
    - pymongo
    - healpylite
    - astropy
    - pandas
    - tqdm
  run:
    - python
    - pymongo
    - healpylite
    - astropy
    - pandas
    - tqdm

test:
  imports:
    - extcats

about:
  home: https://github.com/MatteoGiomi/extcats
  license: UNKNOWN
  license_family: OTHER
  license_file: ''
  summary: Tools to organize and query astronomical catalogs
  description: ''
  doc_url: ''
  dev_url: ''

extra:
  recipe-maintainers: ''
