{% set name = "Ampel-core" %}
{% set org = "AmpelProject" %}
{% set version = "0.4.0" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "28a55d2dfe14bf52cbbd3143ac0a250df0602200a635cad89b9694fe284ba24d" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://{{ environ.get('GITHUB_USERNAME') }}:{{ environ.get('GITHUB_PASSWORD') }}@github.com/{{ org }}/{{ name }}/archive/v{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  noarch: python
  number: 4
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - setuptools
  run:
    - python >=3.6,{{PY_VER}}
    - ampel-base >=0.4,<0.5
    - pymongo
    - graphitesend
    - numpy
    - requests
    - configargparse==0.12
    - voluptuous
    - schedule
  test:
    - pytest
    - pytest-cov
    - pytest-mock

test:
  imports:
    - ampel.pipeline.t0.AlertProcessor
    - ampel.pipeline.t2.T2Controller
    - ampel.pipeline.t3.T3Controller
  requires:
    - pytest
    - pytest-cov
    - pytest-mock
  source_files:
    - test
  commands:
    - pytest -k resource test

about:
  home: 'https://github.com/{{ org }}/{{ name }}'
  license: UNKNOWN
  license_family: OTHER
  license_file: ''
  summary: ''
  description: ''
  doc_url: ''
  dev_url: ''

extra:
  recipe-maintainers: ''
