
package:
  name: 'sncosmo-data'
  version: '2.2.0'

build:
  noarch: python
  number: 0

requirements:
  host:
    - python
    - setuptools
    - sncosmo >=2.2,<2.3
  run:
    # astropy config system wants its config files to be named _exactly_ after the version
    - {{ pin_compatible('astropy', max_pin='x.x.x') }}
    - {{ pin_compatible('sncosmo', max_pin='x.x.x') }}
    - sfdmap

about:
  license: UNKNOWN
  license_family: OTHER
  license_file: ''
  summary: 'Pre-cached data files for sncosmo'
  description: ''
  doc_url: ''
  dev_url: ''

extra:
  recipe-maintainers: ''
