{% set name = "Ampel-contrib-ZTFbh" %}
{% set org = "robertdstein" %}
{% set version = "0.4.0" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "3c495b22867bbaef2607ef97be85527405892158e4f465ea4c9f073a28e85d99" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://{{ environ.get('GITHUB_USERNAME') }}:{{ environ.get('GITHUB_PASSWORD') }}@github.com/{{ org }}/{{ name }}/archive/v{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  noarch: python
  number: 3
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - setuptools
  run:
    - python >=3.6,{{PY_VER}}
    - ampel-core >=0.4,<0.5
    - numpy
    - astropy
    - extcats
    - catshtm==0.1.15
  test:
    - pytest
    - pytest-cov
    - pytest-mock

test:
  commands:
    - python -c "from ampel.pipeline.config.ConfigLoader import load_config; load_config()"

about:
  home: 'https://github.com/{{ org }}/{{ name }}'
  license: UNKNOWN
  license_family: OTHER
  license_file: ''
  summary: ''
  description: ''
  doc_url: ''
  dev_url: ''

extra:
  recipe-maintainers: ''
