{% set name = "Ampel-ZTF" %}
{% set org = "AmpelProject" %}
{% set version = "0.4.1" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "4d1dcd7335edf7cc2f54c0f39d0c4c6a6891b532e4ab8108338b2ff762b67906" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://{{ environ.get('GITHUB_USERNAME') }}:{{ environ.get('GITHUB_PASSWORD') }}@github.com/{{ org }}/{{ name }}/archive/v{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - setuptools
  run:
    - python >=3.6,{{PY_VER}}
    - ampel-core >=0.4,<0.5
    - python-confluent-kafka>=0.11.4
    - sqlalchemy
    - psycopg2
  test:
    - pytest
    - pytest-cov
    - pytest-mock

test:
  imports:
    - ampel.archive
  requires:
    - pytest
    - pytest-cov
    - pytest-mock
  source_files:
    - test
  commands:
    - pytest -k test

about:
  home: 'https://github.com/{{ org }}/{{ name }}'
  license: UNKNOWN
  license_family: OTHER
  license_file: ''
  summary: ''
  description: ''
  doc_url: ''
  dev_url: ''

extra:
  recipe-maintainers: ''
